name: The bitrise action

on: push

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Checking for the PR
      - uses: ./
        with:
          github_token: toto
          bitrise_app_slug: toto
          bitrise_build_trigger_token: toto

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with: 
        milliseconds: 1000
