name: The bitrise action

on:
  push:
    branches: [master]
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          github_token: 503d8295502e1b9ec9b88496c436c3d494bcdd55
          bitrise_app_slug: ca04e0425716e1ce
          bitrise_workflow: "primary"
          bitrise_build_trigger_token: Gs7vZtsWEz-UZ_vNdNxDIA
